---
:test:
  :adapter: sqlite
  :database: $AppPath/db/test.db
:development:
  :adapter: sqlite
  :database: $AppPath/db/judge.db
:product:
  :adapter: mysql2
  :host: localhost
  :database: Juice
  :username:
  :password:
